version: 0.2
phases:
  install:
     runtime-versions:
       python: 3.8     
build:
   commands:
      - sam package --template-file samTemplate.yaml --output-template-file package.yml --s3-bucket test-lambdawidemo
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - package.yml
